-- Tandoori Restaurant - Supabase setup
-- Run this in Supabase Dashboard -> SQL Editor.
-- The website sends new orders to public.orders.

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    phone text not null,
    dish text not null,
    quantity integer not null default 1 check (quantity > 0),
    service_type text not null,
    address text not null,
    notes text,
    created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

-- Allow visitors to submit an order. No read access is granted here.
drop policy if exists "Public can create restaurant orders" on public.orders;
create policy "Public can create restaurant orders"
on public.orders
for insert
to anon, authenticated
with check (true);

-- Reload PostgREST schema cache.
notify pgrst, 'reload schema';
